all:
        gcc -g -o user user.c -lpthread -lrt
        gcc -g -o oss oss.c -lpthread -lrt

clean:
        rm -rf user
        rm -rf oss
        rm -rf *.o
        rm -rf memory_*

run:
        ./oss
